### ISSUE TITLE
Mountpoint not recognised if arguments are forwarded to FUSE

### ISSUE THREAD

**Issue by mariomadproductions** [averne/Fuse-Nx#1]
it seems like fuse-nx doesn't accept a mountpoint argument, if you use the -o argument
e.g.
`fuse-nx mount -o allow_other 9c5a3b56af441ab7b5710011afd27595.nca` works
(mounts to `./9c5a3b56af441ab7b5710011afd27595`)
and
`fuse-nx mount 9c5a3b56af441ab7b5710011afd27595.nca ~/mnt/9c5a3b56af441ab7b5710011afd27595` works
(mounts to `~/mnt/9c5a3b56af441ab7b5710011afd27595`)
but this doesn't work:
`fuse-nx mount -o allow_other 9c5a3b56af441ab7b5710011afd27595.nca ~/mnt/9c5a3b56af441ab7b5710011afd27595`
it says
```
container: File is actually a directory: /home/user/mnt/9c5a3b56af441ab7b5710011afd27595
Run with --help or --help-all for more information.
```

**Comment by averne** [comment]
This is because of how arguments are parsed.
`fuse-nx mount 9c5a3b56af441ab7b5710011afd27595.nca ~/mnt/9c5a3b56af441ab7b5710011afd27595 -o allow_other` should work.

**Comment by mariomadproductions** [comment]
I suppose that makes sense, looking at the order in `--help-all`. It works, thanks.
